# -*- coding: utf-8 -*-
"""제출 파일2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10yDGkgXzV2xoiFIYTKYH9yFfX8SXWSIw

# Library Import
"""

# Library Import
!pip install prophet
import statsmodels.api as sm
from tqdm import tqdm
import numpy as np
import pandas as pd
import datetime as dt
import itertools
from statsmodels.tsa.arima_model import ARIMA

"""# Data Load"""

# Data Load

from google.colab import drive
drive.mount('/content/drive')
data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/공모전/제10회 산업통상자원부 공공데이터활용 BI공모전_빅데이터 분석 과제 1_데이터.xlsx',
                   sheet_name = '2. raw data')
data.head()

data = data[:252]

"""# Prophet"""

from prophet import Prophet

data_KO = pd.DataFrame(data[['기간','한국 수출금액']])
data_KO.columns =['ds','y']
model_KO = Prophet()
model_KO.fit(data_KO)

after_1year = list()
for i in range(1, 13):
  after_1year.append(['2021-%02d-01' % i])
after_1year = pd.DataFrame(after_1year, columns = ['ds'])
after_1year['ds'] = pd.to_datetime(after_1year['ds'])
forecast_KO = model_KO.predict(after_1year)
forecast_KO = forecast_KO[["ds","yhat"]]
forecast_KO.columns = ['기간',"한국 수출금액"]
forecast_KO

data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/공모전/제10회 산업통상자원부 공공데이터활용 BI공모전_빅데이터 분석 과제 1_데이터.xlsx',
                   sheet_name = '2. raw data')
data = data[252:]

def find_RMSE(prediction, groundtruth):
  return np.sqrt(np.mean(np.square(prediction-groundtruth)))

find_RMSE(forecast_KO[['한국 수출금액']].values,data[['한국 수출금액']].values)